# Generated by Django 5.0.7 on 2024-07-17 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2COrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in waiting', 'В ожидании'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='in processing', max_length=20)),
                ('order_name', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('order_time', models.TimeField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number_client', models.CharField(max_length=11)),
                ('name_client', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assigned_orders', to='employees.employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2c_clients', to='employers.employer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
