# Generated by Django 5.0.7 on 2024-07-19 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0001_initial'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2corder',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2c_orders', to='employers.employer'),
        ),
    ]
