# Generated by Django 5.0.7 on 2024-08-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0003_b2corder_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2corder',
            name='status',
            field=models.CharField(choices=[('in_processing', 'В обработке'), ('in_waiting', 'В ожидании'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='in processing', max_length=20),
        ),
    ]
