# Generated by Django 5.0.7 on 2024-08-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0007_alter_b2corder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2corder',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='b2corder',
            name='employee_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
