# Generated by Django 5.0.7 on 2024-08-13 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0008_b2corder_employee_name_b2corder_employee_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2COrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='b2c_client_orders.b2corder')),
            ],
        ),
    ]
