# Generated by Django 5.1 on 2024-08-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0010_b2corder_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2corder',
            name='city',
        ),
    ]
