# Generated by Django 5.1 on 2024-08-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0012_b2corder_city'),
        ('employees', '0002_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2corder',
            name='assigned_employee',
        ),
        migrations.AddField(
            model_name='b2corder',
            name='assigned_employee',
            field=models.ManyToManyField(blank=True, null=True, related_name='%(class)s_assigned_orders', to='employees.employee'),
        ),
    ]
