# Generated by Django 5.1 on 2024-08-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0014_alter_b2corder_assigned_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2corder',
            name='assigned_employee',
        ),
    ]
