# Generated by Django 5.1 on 2024-08-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0016_b2corder_assigned_employee'),
        ('employees', '0002_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2corder',
            name='assigned_employee',
        ),
        migrations.AddField(
            model_name='b2corder',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assigned_orders', to='employees.employee'),
        ),
    ]
