# Generated by Django 5.1 on 2024-08-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0022_alter_b2corder_manager'),
        ('employees', '0002_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2corder',
            name='assigned_employee',
        ),
        migrations.AddField(
            model_name='b2corder',
            name='assigned_employees',
            field=models.ManyToManyField(related_name='%(class)s_assigned_orders', to='employees.employee'),
        ),
    ]
