# Generated by Django 5.1 on 2024-08-30 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0023_remove_b2corder_assigned_employee_and_more'),
        ('employers', '0011_managercityassignment_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2corder',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2c_orders', to='employers.manager'),
        ),
    ]
