# Generated by Django 5.1 on 2024-08-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0025_alter_b2corder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2corder',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='b2corder',
            name='employee_phone',
        ),
    ]
