# Generated by Django 5.1 on 2024-08-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0026_remove_b2corder_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2corder',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
