# Generated by Django 5.1 on 2024-08-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0027_b2corder_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2corder',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b2corder',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='b2corder',
            name='name_client',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b2corder',
            name='order_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='b2corder',
            name='order_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b2corder',
            name='order_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='b2corder',
            name='phone_number_client',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='b2corder',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
