# Generated by Django 5.1 on 2024-09-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0028_alter_b2corder_address_alter_b2corder_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2corder',
            name='scheduled_date',
        ),
    ]
