# Generated by Django 5.1 on 2024-09-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0030_b2corder_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2corder',
            name='created_at',
        ),
    ]
