# Generated by Django 5.1 on 2024-09-24 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0031_remove_b2corder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2corder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
