# Generated by Django 5.1 on 2024-09-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0032_b2corder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2corder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
