# Generated by Django 5.1.1 on 2024-09-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0033_alter_b2corder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2corder',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
