# Generated by Django 5.1.1 on 2024-09-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0034_b2corder_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2corder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
