# Generated by Django 5.1.1 on 2024-10-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c_client_orders', '0037_b2corder_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2corder',
            name='phone_number_client',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
