version: '3.8'

services:
  db:
    image: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "poetry run python manage.py makemigrations &&
             poetry run python manage.py migrate &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_NAME=${POSTGRES_DB}
      - DJANGO_DB_USER=${POSTGRES_USER}
      - DJANGO_DB_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432

volumes:
  postgres_data:
