# Generated by Django 5.0.7 on 2024-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_client_orders', '0002_alter_b2border_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2border',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
