# Generated by Django 5.0.7 on 2024-08-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_client_orders', '0004_alter_b2border_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2border',
            name='status',
            field=models.CharField(choices=[('in_processing', 'В обработке'), ('in_waiting', 'В ожидании'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='in_processing', max_length=20),
        ),
    ]
