# Generated by Django 5.0.7 on 2024-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_client_orders', '0005_alter_b2border_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2border',
            name='status',
            field=models.CharField(choices=[('in waiting', 'В ожидании'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='in processing', max_length=20),
        ),
    ]
