# Generated by Django 5.1 on 2024-08-21 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_client_orders', '0008_b2border_employee_name_b2border_employee_phone'),
        ('orders', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2border',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_orders', to='orders.city'),
        ),
    ]
