# Generated by Django 5.1 on 2024-08-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_client_orders', '0009_b2border_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2border',
            name='city',
        ),
    ]
