# Generated by Django 5.1 on 2024-08-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_client_orders', '0013_alter_b2border_assigned_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2border',
            name='assigned_employee',
        ),
    ]
