# Generated by Django 5.1 on 2024-08-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_client_orders', '0020_alter_b2border_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2border',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='b2border',
            name='employee_phone',
        ),
    ]
