# Generated by Django 5.1 on 2024-09-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_client_orders', '0021_remove_b2border_employee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2border',
            name='scheduled_date',
        ),
    ]
