# Generated by Django 5.1.1 on 2024-09-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_client_orders', '0023_b2border_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2border',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
