# Generated by Django 5.1.1 on 2024-09-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_client_orders', '0024_b2border_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2border',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
