# Generated by Django 5.0.7 on 2024-07-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='orders.order')),
            ],
        ),
    ]
