# Generated by Django 5.0.7 on 2024-07-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b2b_client_orders', '0002_alter_b2border_employer'),
        ('b2c_client_orders', '0002_alter_b2corder_employer'),
        ('employees', '0001_initial'),
        ('schedules', '0002_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees.employee')),
                ('b2b_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='b2b_client_orders.b2border')),
                ('b2c_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='b2c_client_orders.b2corder')),
            ],
        ),
    ]
