# Generated by Django 5.1 on 2024-08-23 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_employer_cities_employer_countries'),
        ('orders', '0012_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.city')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_city_relations', to='employers.employer')),
            ],
            options={
                'unique_together': {('employer', 'city')},
            },
        ),
    ]
