# Generated by Django 5.1 on 2024-08-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_employercity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='countries',
        ),
    ]
