# Generated by Django 5.1 on 2024-08-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_remove_employer_cities_remove_employer_countries'),
        ('orders', '0012_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='selected_cities',
            field=models.ManyToManyField(blank=True, related_name='employers', to='orders.city'),
        ),
        migrations.AddField(
            model_name='employer',
            name='selected_countries',
            field=models.ManyToManyField(blank=True, related_name='employers', to='orders.country'),
        ),
    ]
