# Generated by Django 5.1 on 2024-08-26 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_manager'),
        ('orders', '0012_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerCityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.city')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_assignments', to='employers.employer')),
            ],
            options={
                'unique_together': {('employer', 'city')},
            },
        ),
    ]
