# Generated by Django 5.1 on 2024-08-27 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0008_employercityassignment'),
        ('orders', '0012_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerCityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.city')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_assignments', to='employers.manager')),
            ],
            options={
                'unique_together': {('manager', 'city')},
            },
        ),
    ]
