# Generated by Django 5.1 on 2024-08-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_managercityassignment'),
        ('orders', '0012_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='cities',
            field=models.ManyToManyField(related_name='managers', to='orders.city'),
        ),
    ]
