# Generated by Django 5.1 on 2024-08-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0010_manager_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='managercityassignment',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
