# Generated by Django 5.1 on 2024-09-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0011_managercityassignment_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
