# Generated by Django 5.1 on 2024-09-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0012_employer_first_name_employer_last_name'),
        ('orders', '0013_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='available_payment_methods',
            field=models.ManyToManyField(blank=True, related_name='employers', to='orders.paymentmethod'),
        ),
    ]
