# Generated by Django 5.0.7 on 2024-07-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
