# Generated by Django 5.0.7 on 2024-07-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='in processing', max_length=20),
        ),
    ]
