# Generated by Django 5.0.7 on 2024-07-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='in processing', max_length=20),
        ),
    ]
