# Generated by Django 5.0.7 on 2024-07-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
        ('schedules', '0002_delete_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
