# Generated by Django 5.1 on 2024-08-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_client_orders', '0010_remove_b2border_city'),
        ('b2c_client_orders', '0011_remove_b2corder_city'),
        ('orders', '0010_country_alter_city_name_city_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
